'use client'

import { useMemo, useState, useCallback } from 'react'
import { Search, Wallet, Banknote, CreditCard, ArrowRightLeft, FileText, CheckCircle2, History, X, ArrowUpCircle, ArrowDownCircle, RefreshCw, Printer } from 'lucide-react'
import { toast } from 'react-toastify'

import { currencyFormat } from '@/utils/currency'

const PAYMENT_METHODS = [
  { value: 'CASH', label: 'Cash', icon: Banknote, color: 'from-green-600 to-emerald-600' },
  { value: 'POS', label: 'POS', icon: CreditCard, color: 'from-blue-600 to-indigo-600' },
  { value: 'TRANSFER', label: 'Transfer', icon: ArrowRightLeft, color: 'from-purple-600 to-pink-600' },
  { value: 'OTHER', label: 'Other', icon: FileText, color: 'from-gray-600 to-slate-700' },
]

export default function CustomerDepositPageClient({ slug, storeName = '', initialCustomers = [] }) {
  const [customers, setCustomers] = useState(Array.isArray(initialCustomers) ? initialCustomers : [])
  const [searchTerm, setSearchTerm] = useState('')
  const [selectedCustomerId, setSelectedCustomerId] = useState('')
  const [amount, setAmount] = useState('')
  const [paymentMethod, setPaymentMethod] = useState('CASH')
  const [reference, setReference] = useState('')
  const [remarks, setRemarks] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [successMessage, setSuccessMessage] = useState('')
  const [latestBalance, setLatestBalance] = useState(null)
  const [receipt, setReceipt] = useState(null)

  // Wallet history modal state
  const [historyModal, setHistoryModal] = useState({ open: false, customer: null, transactions: [], loading: false })

  const openHistory = useCallback(async (customer, e) => {
    e.stopPropagation()
    setHistoryModal({ open: true, customer, transactions: [], loading: true })
    try {
      const res = await fetch(`/api/customers/wallet-history?customerId=${customer._id}`)
      const data = await res.json()
      if (!res.ok || !data.success) throw new Error(data.message || 'Failed to load history')
      setHistoryModal((prev) => ({ ...prev, transactions: data.transactions, loading: false }))
    } catch (err) {
      toast.error(err.message || 'Failed to load wallet history')
      setHistoryModal((prev) => ({ ...prev, loading: false, open: false }))
    }
  }, [])

  const closeHistory = useCallback(() => {
    setHistoryModal({ open: false, customer: null, transactions: [], loading: false })
  }, [])

  const handlePrintReceipt = useCallback(() => {
    if (!receipt) return

    const printWindow = window.open('', '_blank', 'width=420,height=760')
    if (!printWindow) {
      toast.error('Unable to open print window. Please allow pop-ups and try again.')
      return
    }

    const storeDisplayName = storeName || receipt.storeName || slug || 'APOS Store'
    const rows = [
      ['Receipt No.', receipt.receiptNumber],
      ['Amount Deposited', currencyFormat(receipt.depositedAmount)],
      ['Outstanding Bill Settled', currencyFormat(receipt.outstandingBillSettled)],
      ['Wallet Balance', currencyFormat(receipt.walletBalance)],
      ['Current Outstanding Bill', currencyFormat(receipt.currentOutstandingBill)],
      ['Payment Method', receipt.paymentMethod],
      ['Reference', receipt.reference || 'N/A'],
      ['Date', new Date(receipt.createdAt).toLocaleString()],
    ]
      .map(([label, value]) => `<tr><td>${label}</td><td style="text-align:right;font-weight:700;">${value}</td></tr>`)
      .join('')

    const html = `
      <!doctype html>
      <html>
      <head>
        <meta charset="utf-8" />
        <title>Deposit Receipt</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; color: #111827; }
          .receipt { border: 1px dashed #9ca3af; border-radius: 12px; padding: 16px; max-width: 360px; margin: 0 auto; }
          h2 { margin: 0 0 6px; font-size: 18px; }
          p { margin: 0 0 14px; color: #4b5563; font-size: 12px; }
          table { width: 100%; border-collapse: collapse; font-size: 13px; }
          td { padding: 8px 0; border-bottom: 1px solid #e5e7eb; }
          .meta { margin-top: 12px; font-size: 11px; color: #6b7280; }
        </style>
      </head>
      <body>
        <div class="receipt">
          <h2>${storeDisplayName}</h2>
          <p>Wallet Deposit Receipt</p>
          <p>${receipt.customerName} • ${slug}</p>
          <table>${rows}</table>
          <div class="meta">Generated by APOS</div>
        </div>
        <script>
          window.onload = function () { window.print(); window.close(); };
        </script>
      </body>
      </html>
    `

    printWindow.document.open()
    printWindow.document.write(html)
    printWindow.document.close()
  }, [receipt, slug, storeName])

  const handlePrintTransactionReceipt = useCallback((txn) => {
    if (!txn) return

    const printWindow = window.open('', '_blank', 'width=420,height=760')
    if (!printWindow) {
      toast.error('Unable to open print window. Please allow pop-ups and try again.')
      return
    }

    const delta = Number(txn.balanceAfter || 0) - Number(txn.balanceBefore || 0)
    const deltaLabel = delta >= 0 ? `+${currencyFormat(delta)}` : currencyFormat(delta)
    const storeDisplayName = storeName || slug || 'APOS Store'
    const rows = [
      ['Transaction ID', txn._id || 'N/A'],
      ['Type', txn.type || 'N/A'],
      ['Amount Change', deltaLabel],
      ['Balance Before', currencyFormat(Number(txn.balanceBefore || 0))],
      ['Balance After', currencyFormat(Number(txn.balanceAfter || 0))],
      ['Payment Method', txn.paymentMethod || 'N/A'],
      ['Reference', txn.reference || 'N/A'],
      ['Date', new Date(txn.createdAt).toLocaleString()],
      ['Recorded By', txn.createdBy || 'N/A'],
    ]
      .map(([label, value]) => `<tr><td>${label}</td><td style="text-align:right;font-weight:700;">${value}</td></tr>`)
      .join('')

    const html = `
      <!doctype html>
      <html>
      <head>
        <meta charset="utf-8" />
        <title>Wallet Transaction Receipt</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; color: #111827; }
          .receipt { border: 1px dashed #9ca3af; border-radius: 12px; padding: 16px; max-width: 360px; margin: 0 auto; }
          h2 { margin: 0 0 6px; font-size: 18px; }
          p { margin: 0 0 14px; color: #4b5563; font-size: 12px; }
          table { width: 100%; border-collapse: collapse; font-size: 13px; }
          td { padding: 8px 0; border-bottom: 1px solid #e5e7eb; }
          .meta { margin-top: 12px; font-size: 11px; color: #6b7280; }
        </style>
      </head>
      <body>
        <div class="receipt">
          <h2>${storeDisplayName}</h2>
          <p>Wallet Transaction Receipt</p>
          <p>${historyModal.customer?.name || 'Customer'} • ${slug}</p>
          <table>${rows}</table>
          ${txn.remarks ? `<div class="meta">Note: ${txn.remarks}</div>` : ''}
          <div class="meta">Generated by APOS</div>
        </div>
        <script>
          window.onload = function () { window.print(); window.close(); };
        </script>
      </body>
      </html>
    `

    printWindow.document.open()
    printWindow.document.write(html)
    printWindow.document.close()
  }, [historyModal.customer, slug, storeName])

  const filteredCustomers = useMemo(() => {
    const term = searchTerm.trim().toLowerCase()
    if (!term) return customers

    return customers.filter((customer) => {
      const name = String(customer?.name || '').toLowerCase()
      const phone = String(customer?.phone || '').toLowerCase()
      const email = String(customer?.email || '').toLowerCase()
      return name.includes(term) || phone.includes(term) || email.includes(term)
    })
  }, [customers, searchTerm])

  const selectedCustomer = useMemo(() => {
    return customers.find((customer) => String(customer?._id) === String(selectedCustomerId)) || null
  }, [customers, selectedCustomerId])

  const displayedBalance = latestBalance ?? Number(selectedCustomer?.walletBalance || 0)

  const handleSubmit = async (event) => {
    event.preventDefault()
    setSuccessMessage('')

    if (!selectedCustomerId) {
      toast.error('Please select a customer')
      return
    }

    const parsedAmount = Number(amount)
    if (!Number.isFinite(parsedAmount) || parsedAmount <= 0) {
      toast.error('Deposit amount must be greater than 0')
      return
    }

    setSubmitting(true)

    try {
      const response = await fetch('/api/customers/deposit', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          customerId: selectedCustomerId,
          amount: parsedAmount,
          paymentMethod,
          reference,
          remarks,
        }),
      })

      const data = await response.json()

      if (!response.ok || !data?.success) {
        throw new Error(data?.message || data?.error || 'Failed to record deposit')
      }

      const updatedBalance = Number(data.walletBalance || 0)
      const creditDeducted = Number(data.creditDeducted || 0)
      const currentOutstandingBill = Number(data.currentOutstandingBill || 0)
      const depositedAmount = Number(data.depositedAmount || parsedAmount)
      const outstandingBillSettled = Number(data.outstandingBillSettled || creditDeducted)
      const receiptNumber = String(data.receiptNumber || `WDR-${Date.now()}`)
      const receiptDate = data.receiptDate || new Date().toISOString()

      setCustomers((prev) => prev.map((customer) => (
        String(customer?._id) === String(selectedCustomerId)
          ? { ...customer, walletBalance: updatedBalance, outstandingBalance: currentOutstandingBill }
          : customer
      )))

      setLatestBalance(updatedBalance)
      setAmount('')
      setPaymentMethod('CASH')
      setReference('')
      setRemarks('')
      setReceipt({
        customerName: selectedCustomer?.name || 'Customer',
        depositedAmount,
        outstandingBillSettled,
        walletBalance: updatedBalance,
        currentOutstandingBill,
        paymentMethod,
        reference,
        receiptNumber,
        createdAt: receiptDate,
      })

      const message = creditDeducted > 0
        ? `Deposit recorded. ${currencyFormat(creditDeducted)} applied to outstanding credits. New wallet balance: ${currencyFormat(updatedBalance)}`
        : `Deposit recorded successfully. New wallet balance: ${currencyFormat(updatedBalance)}`
      setSuccessMessage(message)
      toast.success(message)
    } catch (error) {
      toast.error(error?.message || 'Failed to record deposit')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <>
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50 p-4 sm:p-6 lg:p-8">
      <div className="max-w-5xl mx-auto space-y-6">
        <div className="bg-gradient-to-r from-blue-600 to-indigo-600 rounded-2xl shadow-xl p-6 text-white">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h1 className="text-2xl sm:text-3xl font-bold">Customer Wallet Deposit</h1>
              <p className="mt-2 text-sm text-blue-100">Search a customer, view their wallet balance, and record a new deposit.</p>
            </div>
            <div className="rounded-xl bg-white/15 px-4 py-3 backdrop-blur-sm">
              <p className="text-xs uppercase tracking-[0.2em] text-blue-100">Store</p>
              <p className="text-lg font-semibold">{slug}</p>
            </div>
          </div>
        </div>

        <div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
          <div className="bg-white rounded-2xl shadow-md border border-gray-200 p-5 sm:p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="bg-blue-100 p-3 rounded-xl">
                <Search className="w-5 h-5 text-blue-600" />
              </div>
              <div>
                <h2 className="text-lg font-bold text-gray-900">Find Customer</h2>
                <p className="text-sm text-gray-500">Search by name, phone, or email.</p>
              </div>
            </div>

            <div className="relative mb-4">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
              <input
                type="text"
                value={searchTerm}
                onChange={(event) => setSearchTerm(event.target.value)}
                placeholder="Search customer"
                className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>

            <div className="border border-gray-200 rounded-2xl overflow-hidden bg-gray-50">
              <div className="max-h-[26rem] overflow-y-auto divide-y divide-gray-200">
                {filteredCustomers.length > 0 ? filteredCustomers.map((customer) => {
                  const isSelected = String(customer?._id) === String(selectedCustomerId)

                  return (
                    <div
                      key={String(customer?._id)}
                      className={`transition-all ${isSelected ? 'bg-blue-50 ring-2 ring-inset ring-blue-500' : 'hover:bg-white'}`}
                    >
                      <button
                        type="button"
                        onClick={() => {
                          setSelectedCustomerId(String(customer?._id))
                          setLatestBalance(Number(customer?.walletBalance || 0))
                          setSuccessMessage('')
                        }}
                        className="w-full text-left px-4 pt-4 pb-2"
                      >
                        <div className="flex items-start justify-between gap-3">
                          <div className="min-w-0">
                            <p className="font-semibold text-gray-900 truncate">{customer?.name || 'Unnamed Customer'}</p>
                            <p className="text-sm text-gray-500 truncate">{customer?.phone || 'No phone'}</p>
                            {customer?.email ? <p className="text-xs text-gray-400 truncate">{customer.email}</p> : null}
                          </div>
                          <div className="text-right shrink-0">
                            <p className="text-xs uppercase tracking-wide text-gray-400">Wallet</p>
                            <p className="font-bold text-blue-700">{currencyFormat(Number(customer?.walletBalance || 0))}</p>
                            <p className="mt-1 text-xs uppercase tracking-wide text-gray-400">Outstanding</p>
                            <p className="font-semibold text-amber-700">{currencyFormat(Number(customer?.outstandingBalance || 0))}</p>
                          </div>
                        </div>
                      </button>
                      <div className="px-4 pb-3">
                        <button
                          type="button"
                          onClick={(e) => openHistory(customer, e)}
                          className="flex items-center gap-1.5 text-xs font-semibold text-indigo-600 hover:text-indigo-800 hover:bg-indigo-50 rounded-lg px-2 py-1.5 transition-colors"
                        >
                          <History className="w-3.5 h-3.5" />
                          Wallet History
                        </button>
                      </div>
                    </div>
                  )
                }) : (
                  <div className="px-4 py-10 text-center text-sm text-gray-500">No customers match your search.</div>
                )}
              </div>
            </div>
          </div>

          <div className="space-y-6">
            <div className="bg-white rounded-2xl shadow-md border border-gray-200 p-5 sm:p-6">
              <div className="flex items-center gap-3 mb-4">
                <div className="bg-emerald-100 p-3 rounded-xl">
                  <Wallet className="w-5 h-5 text-emerald-600" />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-gray-900">Wallet Balance</h2>
                  <p className="text-sm text-gray-500">Current balance for the selected customer.</p>
                </div>
              </div>

              <div className="rounded-2xl bg-gradient-to-r from-emerald-600 to-green-600 text-white p-5 shadow-lg">
                <p className="text-sm text-emerald-100">Selected Customer</p>
                <p className="mt-1 text-xl font-bold">{selectedCustomer?.name || 'No customer selected'}</p>
                <p className="mt-4 text-xs uppercase tracking-[0.2em] text-emerald-100">Current Wallet Balance</p>
                <p className="mt-2 text-3xl font-bold">{currencyFormat(displayedBalance)}</p>
                <p className="mt-4 text-xs uppercase tracking-[0.2em] text-emerald-100">Outstanding Balance</p>
                <p className="mt-1 text-xl font-semibold">{currencyFormat(Number(selectedCustomer?.outstandingBalance || 0))}</p>
              </div>
            </div>

            <form onSubmit={handleSubmit} className="bg-white rounded-2xl shadow-md border border-gray-200 p-5 sm:p-6 space-y-5">
              <div>
                <h2 className="text-lg font-bold text-gray-900">Record Deposit</h2>
                <p className="text-sm text-gray-500 mt-1">Enter the deposit details below.</p>
              </div>

              {successMessage ? (
                <div className="flex items-start gap-3 rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-green-800">
                  <CheckCircle2 className="w-5 h-5 shrink-0 mt-0.5" />
                  <p className="text-sm font-medium">{successMessage}</p>
                </div>
              ) : null}

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">Deposit Amount</label>
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  value={amount}
                  onChange={(event) => setAmount(event.target.value)}
                  placeholder="Enter amount"
                  className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-lg font-semibold"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-3">Payment Method</label>
                <div className="grid grid-cols-2 gap-3">
                  {PAYMENT_METHODS.map((method) => {
                    const Icon = method.icon
                    const active = paymentMethod === method.value

                    return (
                      <button
                        key={method.value}
                        type="button"
                        onClick={() => setPaymentMethod(method.value)}
                        className={`flex items-center gap-2 rounded-xl border-2 px-4 py-3 text-sm font-semibold transition-all ${active ? `bg-gradient-to-r ${method.color} text-white border-transparent shadow-md` : 'border-gray-200 text-gray-700 hover:border-gray-300 hover:bg-gray-50'}`}
                      >
                        <Icon className="w-4 h-4" />
                        <span>{method.label}</span>
                      </button>
                    )
                  })}
                </div>
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">Reference</label>
                <input
                  type="text"
                  value={reference}
                  onChange={(event) => setReference(event.target.value)}
                  placeholder="Transaction reference"
                  className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">Remarks</label>
                <textarea
                  value={remarks}
                  onChange={(event) => setRemarks(event.target.value)}
                  rows={4}
                  placeholder="Optional remarks"
                  className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
                />
              </div>

              <button
                type="submit"
                disabled={submitting || !selectedCustomerId}
                className="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 px-6 py-4 text-white font-bold shadow-lg hover:from-blue-700 hover:to-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
              >
                {submitting ? 'Processing Deposit...' : 'Submit Deposit'}
              </button>

              {receipt ? (
                <div className="rounded-2xl border border-dashed border-gray-300 bg-gray-50 p-4 space-y-3">
                  <div className="flex items-center justify-between gap-2">
                    <h3 className="text-sm font-bold text-gray-900">Deposit Receipt</h3>
                    <button
                      type="button"
                      onClick={handlePrintReceipt}
                      className="inline-flex items-center gap-1.5 rounded-lg bg-gray-900 px-3 py-1.5 text-xs font-semibold text-white hover:bg-black"
                    >
                      <Printer className="w-3.5 h-3.5" />
                      Print
                    </button>
                  </div>
                  <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm">
                    <p className="text-gray-500">Receipt No.</p>
                    <p className="text-right font-semibold text-gray-900">{receipt.receiptNumber}</p>
                    <p className="text-gray-500">Amount Deposited</p>
                    <p className="text-right font-semibold text-gray-900">{currencyFormat(receipt.depositedAmount)}</p>
                    <p className="text-gray-500">Outstanding Bill Settled</p>
                    <p className="text-right font-semibold text-amber-700">{currencyFormat(receipt.outstandingBillSettled)}</p>
                    <p className="text-gray-500">Wallet Balance</p>
                    <p className="text-right font-semibold text-emerald-700">{currencyFormat(receipt.walletBalance)}</p>
                    <p className="text-gray-500">Current Outstanding Bill</p>
                    <p className="text-right font-semibold text-red-700">{currencyFormat(receipt.currentOutstandingBill)}</p>
                    <p className="text-gray-500">Payment Method</p>
                    <p className="text-right font-semibold text-gray-900">{receipt.paymentMethod}</p>
                    <p className="text-gray-500">Reference</p>
                    <p className="text-right font-semibold text-gray-900">{receipt.reference || 'N/A'}</p>
                  </div>
                </div>
              ) : null}
            </form>
          </div>
        </div>
      </div>
    </div>

    {/* Wallet History Modal */}
    {historyModal.open && (
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" onClick={closeHistory}>
        <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col" onClick={(e) => e.stopPropagation()}>
          {/* Modal Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 bg-gradient-to-r from-indigo-600 to-blue-600 rounded-t-2xl">
            <div className="flex items-center gap-3">
              <div className="bg-white/20 p-2 rounded-xl">
                <History className="w-5 h-5 text-white" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-white">Wallet History</h3>
                <p className="text-sm text-indigo-100">{historyModal.customer?.name}</p>
              </div>
            </div>
            <button type="button" onClick={closeHistory} className="text-white/70 hover:text-white transition-colors p-1 rounded-lg hover:bg-white/10">
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Modal Body */}
          <div className="overflow-y-auto flex-1 px-5 py-4">
            {historyModal.loading ? (
              <div className="flex flex-col items-center justify-center py-16 gap-3">
                <RefreshCw className="w-8 h-8 text-indigo-400 animate-spin" />
                <p className="text-sm text-gray-500">Loading transactions...</p>
              </div>
            ) : historyModal.transactions.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 gap-3">
                <Wallet className="w-10 h-10 text-gray-300" />
                <p className="text-sm text-gray-500">No wallet transactions found.</p>
              </div>
            ) : (() => {
              const txns = historyModal.transactions
              const openingBalance = txns[0]?.balanceBefore ?? 0
              const currentBalance = txns[txns.length - 1]?.balanceAfter ?? 0
              return (
                <div className="relative">
                  {/* Opening balance */}
                  <div className="flex items-center gap-3 mb-1">
                    <div className="flex flex-col items-center">
                      <div className="w-3 h-3 rounded-full bg-gray-400 shrink-0" />
                      <div className="w-0.5 h-4 bg-gray-200" />
                    </div>
                    <div className="flex items-center justify-between flex-1 bg-gray-50 border border-gray-200 rounded-xl px-4 py-2">
                      <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Opening Balance</span>
                      <span className="text-sm font-bold text-gray-700">{currencyFormat(openingBalance)}</span>
                    </div>
                  </div>

                  {/* Transactions */}
                  {txns.map((txn, idx) => {
                    const isCredit = txn.type === 'Deposit' || txn.type === 'Refund'
                    const delta = txn.balanceAfter - txn.balanceBefore
                    const isLast = idx === txns.length - 1
                    return (
                      <div key={txn._id} className="flex items-start gap-3">
                        <div className="flex flex-col items-center shrink-0 pt-3">
                          <div className={`w-3 h-3 rounded-full shrink-0 ${isCredit ? 'bg-green-500' : 'bg-red-400'}`} />
                          {!isLast && <div className="w-0.5 flex-1 bg-gray-200 my-1" style={{ minHeight: '2rem' }} />}
                        </div>
                        <div className={`flex-1 mb-2 rounded-xl border px-4 py-3 ${
                          isCredit ? 'border-green-100 bg-green-50' : 'border-red-100 bg-red-50'
                        }`}>
                          <div className="flex items-center justify-between gap-2">
                            <div className="flex items-center gap-2">
                              {isCredit
                                ? <ArrowUpCircle className="w-4 h-4 text-green-600 shrink-0" />
                                : <ArrowDownCircle className="w-4 h-4 text-red-500 shrink-0" />}
                              <span className="text-sm font-bold text-gray-900">{txn.type}</span>
                            </div>
                            <div className="flex items-center gap-2">
                              <span className={`text-sm font-extrabold ${isCredit ? 'text-green-700' : 'text-red-600'}`}>
                                {delta >= 0 ? '+' : ''}{currencyFormat(delta)}
                              </span>
                              <button
                                type="button"
                                onClick={() => handlePrintTransactionReceipt(txn)}
                                className="inline-flex items-center gap-1 rounded-md border border-gray-300 bg-white px-2 py-1 text-[11px] font-semibold text-gray-700 hover:bg-gray-100"
                              >
                                <Printer className="w-3.5 h-3.5" />
                                Print
                              </button>
                            </div>
                          </div>
                          <div className="flex items-center justify-between mt-1.5">
                            <span className="text-xs text-gray-500">
                              {txn.paymentMethod || ''}{txn.reference ? ` · ${txn.reference}` : ''}
                            </span>
                            <span className="text-xs font-semibold text-gray-600">Balance: {currencyFormat(txn.balanceAfter)}</span>
                          </div>
                          {txn.remarks ? (
                            <p className="text-xs text-gray-400 mt-1 break-words">{txn.remarks}</p>
                          ) : null}
                          <p className="text-xs text-gray-400 mt-1">
                            {new Date(txn.createdAt).toLocaleString()} · {txn.createdBy}
                          </p>
                        </div>
                      </div>
                    )
                  })}

                  {/* Current balance */}
                  <div className="flex items-center gap-3">
                    <div className="w-3 h-3 rounded-full bg-indigo-500 shrink-0" />
                    <div className="flex items-center justify-between flex-1 bg-indigo-50 border border-indigo-200 rounded-xl px-4 py-2">
                      <span className="text-xs font-semibold text-indigo-600 uppercase tracking-wider">Current Balance</span>
                      <span className="text-base font-extrabold text-indigo-700">{currencyFormat(currentBalance)}</span>
                    </div>
                  </div>
                </div>
              )
            })()}
          </div>

          {/* Modal Footer */}
          {!historyModal.loading && historyModal.transactions.length > 0 && (
            <div className="px-6 py-3 border-t border-gray-100 text-xs text-gray-400 text-center">
              {historyModal.transactions.length} transaction{historyModal.transactions.length !== 1 ? 's' : ''} · oldest to newest
            </div>
          )}
        </div>
      </div>
    )}
  </>
  )
}
