export const subs = [
    {
        name: 'basic',   
        price: 3000,    
        maxMenu: 20,
        maxProduct: 100,
        maxStoreUser: 1,
        features:[
           'accept Orders',
           'accept Payments',
          'Manage Orders',
           'Full access to QR tool',
            'Access to the menu creation tool',
           'Unlimited views',
            '20 items in the menu',
            '100 orders monthly',
            'Community support.',
        ]
    },
    {
        name: 'premium',
       price: 5000,
        maxMenu: 10,
        maxProduct: 100,
        maxStore: 20,
        maxStoreUser: 1,
        features:[
           'accept Orders',
           'accept Payments',
          'Manage Orders',
           'Full access to QR tool',
            'Access to the menu creation tool',
           'Unlimited views',
            '40 items in the menu',
            '300 orders monthly',
            'Community support.',
        ]
    },
    {
        name: 'Exclusive', 
        price: 10000,      
        maxMenu: 10,
        maxProduct: 100,
        maxStore: 20,
        maxStoreUser: 1,
        features:[
           'accept Orders',
          'Manage Orders',
           'Full access to QR tool',
            'Access to the menu creation tool',
           'Unlimited views',
            'unlimited items in the menu',
            'unlimited orders monthly',
            'Community support.',
        ]
    },
    {
        name: 'Hotel', 
        price: 5000,      
        maxMenu: 3,
        maxProduct: 40,
        maxStore: 20,
        maxStoreUser: 1,
        features:[
           'Book Rooms',
           'accept Orders',
          'Manage Rooms',
          'Manage Orders',
           'Full access to QR tool',
            'Access to the menu creation tool',
           'Unlimited views',
            '40 items in the menu',
            'unlimited orders monthly',
            'Community support.',
        ]
    },
    {
        name: 'Hotel Pro', 
        price: 10000,      
        maxMenu: 10,
        maxProduct: 100,
        maxStore: 20,
        maxStoreUser: 1,
        features:[
           'Book Rooms',
           'accept Orders',
          'Manage Orders',
          'Manage Rooms',
           'Full access to QR tool',
            'Access to the menu creation tool',
           'Unlimited views',
            'unlimited items in the menu',
            'unlimited orders monthly',
            'Community support.',
        ]
    },
]